version: "3.9" # opsiyonel.

services:

  frontend:
    # container_name: frontend # (default:key)
    image: "docker-compose-frontend" # image_name
    build: ./frontend # The folder to be dockerized (dockerfile)
    ports: # external/internal port numbers
      - 3000:3000
      - 80:3000
    restart: on-failure # rerun on error.
    depends_on: # run the following first
      - backend # defined below.

  backend:
    # container_name: backend # (default:key)
    image: "docker-compose-backend" # image_name
    build: ./backend # The folder to be dockerized (dockerfile)
    ports: # external/internal port numbers
      - 8000:8000
    restart: on-failure # rerun on error.
    volumes: # physical ways (external:internal)
      - $PWD/backend/db.sqlite3:/backend/db.sqlite3
      - db_data:/var/lib/postgresql/data